export default {

	products: [
		{
			_id: "1",
			name: 'Kaju',
			image: '/images/DryFruits/Kaju210.jpg',
			price: 1400,
			weight: '/kg',
			brand: 'Kaju-210',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "2",
			name: 'Kaju',
			image: '/images/DryFruits/Kaju240.jpg',
			price: 1300,
			weight: '/kg',
			brand: 'Kaju-240',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "3",
			name: 'Kaju',
			image: '/images/DryFruits/Kaju320.jpg',
			price: 1200,
			weight: '/kg',
			brand: 'Kaju-320',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "4",
			name: 'Kaju',
			image: '/images/DryFruits/Kaju400.jpg',
			price: 1000,
			weight: '/kg',
			brand: 'Kaju-400',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "5",
			name: 'Kaju',
			image: '/images/DryFruits/KajuTukda.jpg',
			price: 840,
			weight: '/kg',
			brand: 'Kaju-Tukda',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "6",
			name: 'Badam',
			image: '/images/DryFruits/BadamRegular.jpg',
			price: 900,
			weight: '/kg',
			brand: 'Regular',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "7",
			name: 'Badam',
			image: '/images/DryFruits/BadamBig.jpg',
			price: 1050,
			weight: '/kg',
			brand: 'Badam-Big',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "8",
			name: 'Badam',
			image: '/images/DryFruits/BadamMamro.jpg',
			price: 2500,
			weight: '/kg',
			brand: 'Badam-Mamro',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "9",
			name: 'Jaldaru',
			image: '/images/DryFruits/JaldaruSmall.jpg',
			price: 800,
			weight: '/kg',
			brand: 'Small',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "10",
			name: 'Jaldaru',
			image: '/images/DryFruits/JaldaruMedium.jpg',
			price: 1000,
			weight: '/kg',
			brand: 'Medium',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "11",
			name: 'Jaldaru',
			image: '/images/DryFruits/JaldaruBig.jpg',
			price: 1400,
			weight: '/kg',
			brand: 'Big',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "12",
			name: 'Akhrot',
			image: '/images/DryFruits/AkhrotSmall.jpeg',
			price: 1500,
			weight: '/kg',
			brand: 'Small',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "13",
			name: 'Akhrot',
			image: '/images/DryFruits/AkhrotBig.jpeg',
			price: 1800,
			weight: '/kg',
			brand: 'Big',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "14",
			name: 'Akhrot',
			image: '/images/DryFruits/AkhrotTukda.jpg',
			price: 1200,
			weight: '/kg',
			brand: 'Tukda',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "15",
			name: 'Pista',
			image: '/images/DryFruits/Pistaa.jpg',
			price: 1800,
			weight: '/kg',
			brand: 'Normal',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "16",
			name: 'Draksh',
			image: '/images/DryFruits/Draksh.jpg',
			price: 360,
			weight: '/kg',
			brand: 'Indian',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "17",
			name: 'Draksh',
			image: '/images/DryFruits/DrakshBlack.jpg',
			price: 600,
			weight: '/kg',
			brand: 'Black',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "18",
			name: 'Anjeer',
			image: '/images/DryFruits/AnjeerMedium.jpeg',
			price: 1400,
			weight: '/kg',
			brand: 'Medium',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "19",
			name: 'Anjeer',
			image: '/images/DryFruits/AnjeerBig.jpeg',
			price: 1800,
			weight: '/kg',
			brand: 'Big',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "20",
			name: 'Kharek',
			image: '/images/DryFruits/KharekRed.jpg',
			price: 280,
			weight: '/kg',
			brand: 'Red',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "21",
			name: 'Kharek',
			image: '/images/DryFruits/kharekBlack.jpg',
			price: 280,
			weight: '/kg',
			brand: 'Black',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'dryfruit'
		},
		{
			_id: "22",
			name: 'Boondi Laddo',
			image: '/images/DesiSweets/BoondiLadoo.jpg',
			price: 280,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "23",
			name: 'Khaja',
			image: '/images/DesiSweets/khaja.jpg',
			price: 280,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "24",
			name: 'Khopra Pak',
			image: '/images/DesiSweets/khopraPak.jpg',
			price: 320,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "25",
			name: 'Maysor Pak',
			image: '/images/DesiSweets/MaysorPak.jpg',
			price: 280,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "26",
			name: 'Mohanthal',
			image: '/images/DesiSweets/Mohanthal.jpg',
			price: 380,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "27",
			name: 'Motichoor Laddo',
			image: '/images/DesiSweets/MotichoorLadoo.jpg',
			price: 380,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "28",
			name: 'Mumbai Halwa',
			image: '/images/DesiSweets/MumbaiHalwa.jpg',
			price: 220,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "29",
			name: 'Rabar Halwa',
			image: '/images/DesiSweets/RabarHalwa.jpg',
			price: 240,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "30",
			name: 'Sonpapdi',
			image: '/images/DesiSweets/Sonpapdi.jpg',
			price: 280,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'desisweets'
		},
		{
			_id: "31",
			name: 'Dry Fruit Chikki',
			image: '/images/DryFruitChikki/DryFruitChikki.jpg',
			price: 800,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "32",
			name: 'Kaju Chikki',
			image: '/images/DryFruitChikki/KajuChikki.jpeg',
			price: 750,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "33",
			name: 'Coconut Chikki',
			image: '/images/DryFruitChikki/KhopraChikki.jpg',
			price: 280,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "34",
			name: 'Special Mix Chikki',
			image: '/images/DryFruitChikki/MixChikki.jpg',
			price: 380,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "35",
			name: 'Plain Chikki',
			image: '/images/DryFruitChikki/PlainChikki.jpg',
			price: 280,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "36",
			name: 'Sing Chikki',
			image: '/images/DryFruitChikki/SingChikki.jpg',
			price: 280,
			weight: '/kg',
			brand: 'Peanuts',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "37",
			name: 'Til Chikki',
			image: '/images/DryFruitChikki/TilChikki.jpg',
			price: 280,
			weight: '/kg',
			brand: 'Seasam',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'chikki'
		},
		{
			_id: "38",
			name: 'Chocolate Kalakand',
			image: '/images/MilkSweets/ChocolateKalakand.jpg',
			price: 440,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'milksweets'
		},
		{
			_id: "39",
			name: 'Kalakand',
			image: '/images/MilkSweets/Kalakand.jpg',
			price: 440,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'milksweets'
		},
		{
			_id: "40",
			name: 'Malai Kesar Peda',
			image: '/images/MilkSweets/MalaiKesarPeda.jpeg',
			price: 480,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'milksweets'
		},
		{
			_id: "41",
			name: 'Malai Peda',
			image: '/images/MilkSweets/MalaiPeda.jpg',
			price: 440,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'milksweets'
		},
		{
			_id: "42",
			name: 'Malai Puri Kesar',
			image: '/images/MilkSweets/MalaiPuriKesar.jpg',
			price: 440,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'milksweets'
		},
		{
			_id: "43",
			name: 'Malai Puri',
			image: '/images/MilkSweets/MalaiPuriWhite.jpg',
			price: 400,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'milksweets'
		},
		{
			_id: "44",
			name: 'Badam Katli',
			image: '/images/Sweets/BadamKatli.jpeg',
			price: 800,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'sweets'
		},
		{
			_id: "45",
			name: 'Dry Fruit Roll',
			image: '/images/Sweets/DryFruitsRoll.jpg',
			price: 880,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'sweets'
		},
		{
			_id: "46",
			name: 'Kaju Katli',
			image: '/images/Sweets/KajuKatli.jpg',
			price: 800,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'sweets'
		},
		{
			_id: "47",
			name: 'Kaju Roll',
			image: '/images/Sweets/KajuRoll.jpg',
			price: 800,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'sweets'
		},
		{
			_id: "48",
			name: 'Kesar Kaju Katli',
			image: '/images/Sweets/KesarKatli.jpg',
			price: 840,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'sweets'
		},
		{
			_id: "49",
			name: 'Mix Dry Fruit Sweets',
			image: '/images/Sweets/MixDryFruitsSweets.jpg',
			price: 1200,
			weight: '/kg',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'sweets'
		},
		{
			_id: "50",
			name: 'Special DryFruits',
			image: '/images/Special/special1.jpeg',
			price: 1080,
			weight: '/800gms',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'special'
		},
		{
			_id: "51",
			name: 'Special DryFruits',
			image: '/images/Special/special2.jpeg',
			price: 780,
			weight: '/600gms',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'special'
		},
		{
			_id: "52",
			name: 'Special DryFruits',
			image: '/images/Special/special3.jpeg',
			price: 400,
			weight: '/300gms',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'special'
		},
		{
			_id: "53",
			name: 'Special DryFruits',
			image: '/images/Special/special4.jpeg',
			price: 1080,
			weight: '/800gms',
			brand: '',
			rating: 4,
			numReviews: 10,
			countInStock: 6,
			category: 'special'
		}

	]
}
